- name: Install Apache
  dnf:
    name: httpd
    state: latest

- name: Install PHP
  dnf:
    name:
      - php
      - php-mysqli
      - php-json

- name: Allow htttpd to make network connections
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Start Apache
  service:
    name: httpd
    state: started
    enabled: yes