- name: Install Apache
  dnf:
    name: httpd
    state: latest

- name: Install PHP
  dnf:
    name:
      - php
      - php-mysqli

- name: Start Apache
  service:
    name: httpd
    state: started
    enabled: yes